[package]
name = "colosseum"
version = "0.1.0"
edition = "2021"

[dependencies]
kiss3d = "0.35.0"
rand = "0.9.0"
rapier3d = { version = "0.24.0", features = ["simd-stable"] }
zenoh = "1.4.0"
zenoh-ext = "1.4.0"
tokio = "1"